# EICC-GeSI template
# Version: 3.01
#
---
:worksheet_indices:
  :declaration: 3
  :minerals: 3
  :company_level: 3
  :smelter_list: 4
  :smelter_names: 5
:fields:
  :declaration:
    - :company_name
    - :declaration_scope
    - :description_of_scope
    - :language
    - :company_unique_identifier
    - :company_unique_id_authority
    - :address
    - :contact_name
    - :contact_email
    - :contact_phone
    - :authorizer
    - :authorizer_title
    - :authorizer_email
    - :authorizer_phone
    - :effective_date
  :minerals:
    # Question 1
    -
      -
        - :question
      -
        - :tantalum
        - :tantalum_comment
      -
        - :tin
        - :tin_comment
      -
        - :gold
        - :gold_comment
      -
        - :tungsten
        - :tungsten_comment
      -
        -
    # Question 2
    -
      -
        - :question
      -
        - :tantalum
        - :tantalum_comment
      -
        - :tin
        - :tin_comment
      -
        - :gold
        - :gold_comment
      -
        - :tungsten
        - :tungsten_comment
      -
        -
    # Question 3
    -
      -
        - :question
      -
        - :tantalum
        - :tantalum_comment
      -
        - :tin
        - :tin_comment
      -
        - :gold
        - :gold_comment
      -
        - :tungsten
        - :tungsten_comment
      -
        -
    # Question 4
    -
      -
        - :question
      -
        - :tantalum
        - :tantalum_comment
      -
        - :tin
        - :tin_comment
      -
        - :gold
        - :gold_comment
      -
        - :tungsten
        - :tungsten_comment
      -
        -
    # Question 5
    -
      -
        - :question
      -
        - :tantalum
        - :tantalum_comment
      -
        - :tin
        - :tin_comment
      -
        - :gold
        - :gold_comment
      -
        - :tungsten
        - :tungsten_comment
      -
        -
    # Question 6
    -
      -
        - :question
      -
        - :tantalum
        - :tantalum_comment
      -
        - :tin
        - :tin_comment
      -
        - :gold
        - :gold_comment
      -
        - :tungsten
        - :tungsten_comment
      -
        -
    # Question 7
    -
      -
        - :question
      -
        - :tantalum
        - :tantalum_comment
      -
        - :tin
        - :tin_comment
      -
        - :gold
        - :gold_comment
      -
        - :tungsten
        - :tungsten_comment
      -
        -
  :company_level:
    # Question A
    -
      - :question
      - :answer
      - :comment
    # Question B
    -
      - :question
      - :answer
      - :comment
    # Question C
    -
      - :question
      - :answer
      - :comment
    # Question D
    -
      - :question
      - :answer
      - :comment
    # Question E
    -
      - :question
      - :answer
      - :comment
    # Question F
    -
      - :question
      - :answer
      - :comment
    # Question G
    -
      - :question
      - :answer
      - :comment
    # Question H
    -
      - :question
      - :answer
      - :comment
    # Question I
    -
      - :question
      - :answer
      - :comment
    # Question J
    -
      - :question
      - :answer
      - :comment
  :smelter_list:
    - :metal
    - :smelter_reference_list
    - :standard_smelter_name
    - :facility_location_country
    - :smelter_id
    - :source_of_smelter_id
    - :facility_location_street_address
    - :facility_location_city
    - :facility_location_province
    - :facility_contact_name
    - :facility_contact_email
    - :proposed_next_steps
    - :mineral_source
    - :mineral_source_location
    - :is_all_smelter_feedstock_from_recycled_sources
    - :comment
  :smelter_names:
    - :metal
    - :standard_smelter_name
    - :known_alias
    - :facility_location_country
    - :smelter_id
