# CFSI template
# Version: 2.00
#
---
:declaration:
  :company_name:
    :row: 6
    :column: 3
  :declaration_scope:
    :row: 7
    :column: 3
  :description_of_scope:
    :row: 8
    :column: 3
  :language:
    :row: 1
    :column: 3
  :company_unique_identifier:
    :row: 10
    :column: 3
  :address:
    :row: 11
    :column: 3
  :authorized_company_representative_name:
    :row: 12
    :column: 3
  :contact_title:
    :row: 13
    :column: 3
  :contact_email:
    :row: 14
    :column: 3
  :contact_phone:
    :row: 15
    :column: 3
  :completion_at:
    :row: 16
    :column: 3
:minerals:
  :start_row: 19
  :question: 1
  :tantalum: 3
  :tantalum_comment: 6
  :tin: 3
  :tin_comment: 6
  :gold: 3
  :gold_comment: 6
  :tungsten: 3
  :tungsten_comment: 6
:company_level:
  :start_row: 57
  :question: 1
  :answer: 3
  :comment: 6
:smelter_list:
  :start_row: 3
  :smelter_id: 0
  :metal: 1
  :smelter_reference_list: 2
  :standard_smelter_name: 3
  :facility_location_country: 4
  :facility_location_street_address: 5
  :facility_location_city: 6
  :facility_location_province: 7
  :facility_contact_name: 8
  :facility_contact_email: 9
  :proposed_next_steps: 10
  :mineral_source: 11
  :mineral_source_location: 12
  :comment: 13
:standard_smelter_name:
  :start_row: 2
  :metal: 0
  :standard_smelter_name: 1
  :known_alias: 2
  :facility_location_country: 3
  :smelter_id: 4
